language: java

jdk:
  - openjdk10

addons:
  sonarcloud:
    organization: "robinvdbroeck-github" # the key of the org you chose at step #3

script:
  -  mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
    - '$HOME/.sonar/cache'
    - '$HOME/.m2/repository'