language: java

jdk:
  - openjdk11

addons:
  sonarcloud:
    organization: "robinvdbroeck-github" # the key of the org you chose at step #3
    token:
      secure: SONAR_TOKEN

script:
- sonar-scanner

cache:
  directories:
  - '$HOME/.sonar/cache'